### ISSUE TITLE
Github 101 training

### ISSUE THREAD

**Issue by hackajesse** [sfbrigade/core-team#1]
Try to source from other, existing trainings unless those aren't very good. In which case, create our own!

**Comment by hackajesse** [comment]
could be titled Collaborative Coding 101 (github training)

**Comment by jszwedko** [comment]
:+1: to this

**Comment by gregboyer** [comment]
Adding to workshop/event brainstorming doc

**Comment by jszwedko** [comment]
:+1: if you do move forward with this, @thfield has done these in the past and may be up for doing it again.
