### ISSUE TITLE
Big, Annual Events

### ISSUE THREAD

**Issue by hackajesse** [sfbrigade/core-team#14]
CityCamp - mid-January
CodeAcross - late-February
NDOCH - early June
Summit (CfA plans it, but how can we coordinate an event in SF every year for those who can't go to Summit)

These should happen every year automatically. Someone needs to coordinate and plan each one months in advance.

**Comment by hackajesse** [comment]
[CityCamp Oakland Eventbrite 2016](https://www.eventbrite.com/e/citycamp-oakland-2016-registration-20541739897)

**Comment by gregboyer** [comment]
Tracked in google docs
