### ISSUE TITLE
Trainings / Workshops

### ISSUE THREAD

**Issue by hackajesse** [sfbrigade/core-team#16]
What trainings do we want to offer? (one to many teaching)
What workshops do we want to offer? (few to few collaboration)

Plan to record these somehow so we can put them online!

Comment!

**Comment by hackajesse** [comment]
How to get a partnership with the City on your project. (training) /cc @jasonlally 
How to do user research. (workshop) /cc @MissPaaj 
How to plan a project launch. (workshop) /cc @sfbrigade/core-project-launch 
How to work with a community partner. (training) /cc @j6design

**Comment by gregboyer** [comment]
Migrating to an event brainstorming doc
