### ISSUE TITLE
Create brigade CRM

### ISSUE THREAD

**Issue by hackajesse** [sfbrigade/core-team#19]
for tracking business development opportunities (both paid and unpaid - likely the latter) with outside organizations & govt

for tracking potential sponsors

for tracking our network of resources

/cc @sfbrigade/core-website-tools

**Comment by jszwedko** [comment]
I'd suggest keeping this simple at first and just using a Google spreadsheet -- if it becomes unmanageable we can consider something more complex.

**Comment by gregboyer** [comment]
Transfered to task
