### ISSUE TITLE
Share Brigade values on website

### ISSUE THREAD

**Issue by hackajesse** [sfbrigade/core-team#24]
Need to make these a bit higher quality in terms of descriptiveness, but definitely ultimately on the website (or even in their rough state with a feedback option?)

/cc @sfbrigade/core-website-tools

**Comment by jszwedko** [comment]
Yes! This is definitely something that we've talked about, but haven't gotten to yet.

**Comment by gregboyer** [comment]
transfered to https://github.com/orgs/sfbrigade/projects/1
