### ISSUE TITLE
Get hack night coordinator

### ISSUE THREAD

**Issue by hackajesse** [sfbrigade/core-team#25]
Tasks: 
- update the hack night meetup page as events are organized (not the night before)
- update the agenda for the evening w/any special notes
- improve the links and info on the meetup page
- coordinate the brigade calendar
- collaborate with finance person to ensure food is paid for
- ensure food arrives on time
- ensure project launch and member support teams have the necessary resources they need at hack night
- coordinate speakers, event / other announcements
- update Welcome to Hack Night deck and collaborate with W&TT on its public facing nature

**Comment by gregboyer** [comment]
All available in the hack-night document.
