### ISSUE TITLE
Get finances coordinator

### ISSUE THREAD

**Issue by hackajesse** [sfbrigade/core-team#26]
Tasks:
- Regularly track expenses (largely just catering and name tags)
- Update Core Team leads on our finances monthly
- Submit expense reports as appropriate
- Research opportunities to raise funds via grants and competitions
- Work with others as appropriate to apply for grants/competitions in a timely manner
- Forecast SF Brigade's financial obligations throughout its growth
- Work with Core Team leads on budgeting for the year, including any internal trainings, significant events, etc.

**Comment by gregboyer** [comment]
That's me!
